spring.application.name=back

# 1. \u4F3A\u670D\u5668\u901A\u8A0A\u57E0 (\u9810\u8A2D\u70BA 8080)
server.port=8050

# 2. \u8CC7\u6599\u5EAB\u9023\u7DDA\u8CC7\u8A0A (\u9023\u7DDA\u5230 XAMPP \u7684 library_system \u8CC7\u6599\u5EAB)
spring.datasource.url=jdbc:mysql://localhost:3306/library_system?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

# 3. \u6307\u5B9A MySQL \u7684\u9A45\u52D5\u7A0B\u5F0F
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 4. JPA / Hibernate \u8A2D\u5B9A
# \u8B93\u63A7\u5236\u53F0\u5370\u51FA\u57F7\u884C\u7684 SQL \u6307\u4EE4\uFF08\u65B9\u4FBF\u6211\u5011\u9664\u932F\uFF09
spring.jpa.show-sql=true
# \u4FDD\u6301\u8CC7\u6599\u5EAB\u7D50\u69CB\uFF0C\u4E0D\u8981\u8B93 Spring Boot \u81EA\u52D5\u4E82\u6539\u4F60\u5EFA\u597D\u7684\u8868\u683C
spring.jpa.hibernate.ddl-auto=validate